In [1]:
import pandas as pd
import yfinance as yf
from pathlib import Path

In [2]:
base_path = Path("..")
universe_path = base_path / "data" / "external" / "universe.csv"
raw_path = base_path / "data" / "raw"
processed_path = base_path / "data" / "processed"

raw_path.mkdir(parents=True, exist_ok=True)
processed_path.mkdir(parents=True, exist_ok=True)

print(universe_path)

..\data\external\universe.csv

In [3]:
universe = pd.read_csv(universe_path)
universe.head()

  ticker             company  subtheme
0   CRWD         CrowdStrike  endpoint
1   PANW  Palo Alto Networks  platform
2   FTNT            Fortinet   network
3   TENB             Tenable  endpoint
4      S         SentinelOne  endpoint

In [4]:
tickers = universe["ticker"].tolist()
tickers

['CRWD',
 'PANW',
 'FTNT',
 'TENB',
 'S',
 'OKTA',
 'CYBR',
 'ZS',
 'NET',
 'AKAM',
 'CSCO',
 'JNPR',
 'NTGR',
 'SNPS',
 'PLTR',
 'OTEX',
 'RPD',
 'CHKP',
 'GEN',
 'QLYS']

In [5]:
start_date = "2018-01-01"
end_date = "2026-01-01"

data = yf.download(
    tickers=tickers,
    start=start_date,
    end=end_date,
    auto_adjust=False,
    group_by="ticker",
    progress=False
)

data.head()

$JNPR: possibly delisted; no timezone found

1 Failed download:
['JNPR']: possibly delisted; no timezone found

Ticker           PANW                                                       \
Price            Open       High        Low      Close  Adj Close   Volume
Date
2018-01-02  24.333332  24.811666  24.183332  24.758333  24.758333  4578000
2018-01-03  24.801666  24.991667  24.753332  24.946667  24.946667  4934400
2018-01-04  24.993334  25.438334  24.808332  24.876667  24.876667  6803400
2018-01-05  25.170000  25.514999  24.996668  25.495001  25.495001  8448000
2018-01-08  25.368334  25.674999  25.281668  25.608334  25.608334  6874800

Ticker     TENB                 ...   FTNT                            JNPR  \
Price      Open High Low Close  ...    Low  Close Adj Close    Volume Open
Date                            ...
2018-01-02  NaN  NaN NaN   NaN  ...  8.712  8.870     8.870   6443500  NaN
2018-01-03  NaN  NaN NaN   NaN  ...  8.834  9.006     9.006   7572500  NaN
2018-01-04  NaN  NaN NaN   NaN  ...  8.792  8.800     8.800  12654500  NaN
2018-01-05  NaN  NaN NaN   NaN  ...  8.784  8.820     8.820   7152000  NaN
2018-01-08  NaN  NaN NaN   NaN  ...  8.802  9.000     9.000   5955000  NaN

Ticker
Price      High Low Close Adj Close Volume
Date
2018-01-02  NaN NaN   NaN       NaN    NaN
2018-01-03  NaN NaN   NaN       NaN    NaN
2018-01-04  NaN NaN   NaN       NaN    NaN
2018-01-05  NaN NaN   NaN       NaN    NaN
2018-01-08  NaN NaN   NaN       NaN    NaN

[5 rows x 120 columns]

In [6]:
data.to_pickle(raw_path / "prices_raw.pkl")
print("Saved raw price data to:", raw_path / "prices_raw.pkl")

Saved raw price data to: ..\data\raw\prices_raw.pkl

In [7]:
data = pd.read_pickle(raw_path / "prices_raw.pkl")
data.head()

Ticker           PANW                                                       \
Price            Open       High        Low      Close  Adj Close   Volume
Date
2018-01-02  24.333332  24.811666  24.183332  24.758333  24.758333  4578000
2018-01-03  24.801666  24.991667  24.753332  24.946667  24.946667  4934400
2018-01-04  24.993334  25.438334  24.808332  24.876667  24.876667  6803400
2018-01-05  25.170000  25.514999  24.996668  25.495001  25.495001  8448000
2018-01-08  25.368334  25.674999  25.281668  25.608334  25.608334  6874800

Ticker     TENB                 ...   FTNT                            JNPR  \
Price      Open High Low Close  ...    Low  Close Adj Close    Volume Open
Date                            ...
2018-01-02  NaN  NaN NaN   NaN  ...  8.712  8.870     8.870   6443500  NaN
2018-01-03  NaN  NaN NaN   NaN  ...  8.834  9.006     9.006   7572500  NaN
2018-01-04  NaN  NaN NaN   NaN  ...  8.792  8.800     8.800  12654500  NaN
2018-01-05  NaN  NaN NaN   NaN  ...  8.784  8.820     8.820   7152000  NaN
2018-01-08  NaN  NaN NaN   NaN  ...  8.802  9.000     9.000   5955000  NaN

Ticker
Price      High Low Close Adj Close Volume
Date
2018-01-02  NaN NaN   NaN       NaN    NaN
2018-01-03  NaN NaN   NaN       NaN    NaN
2018-01-04  NaN NaN   NaN       NaN    NaN
2018-01-05  NaN NaN   NaN       NaN    NaN
2018-01-08  NaN NaN   NaN       NaN    NaN

[5 rows x 120 columns]

In [8]:
data.columns

MultiIndex([('PANW',      'Open'),
            ('PANW',      'High'),
            ('PANW',       'Low'),
            ('PANW',     'Close'),
            ('PANW', 'Adj Close'),
            ('PANW',    'Volume'),
            ('TENB',      'Open'),
            ('TENB',      'High'),
            ('TENB',       'Low'),
            ('TENB',     'Close'),
            ...
            ('FTNT',       'Low'),
            ('FTNT',     'Close'),
            ('FTNT', 'Adj Close'),
            ('FTNT',    'Volume'),
            ('JNPR',      'Open'),
            ('JNPR',      'High'),
            ('JNPR',       'Low'),
            ('JNPR',     'Close'),
            ('JNPR', 'Adj Close'),
            ('JNPR',    'Volume')],
           names=['Ticker', 'Price'], length=120)

In [9]:
data.columns.levels[0].tolist()

['AKAM',
 'CHKP',
 'CRWD',
 'CSCO',
 'CYBR',
 'FTNT',
 'GEN',
 'JNPR',
 'NET',
 'NTGR',
 'OKTA',
 'OTEX',
 'PANW',
 'PLTR',
 'QLYS',
 'RPD',
 'S',
 'SNPS',
 'TENB',
 'ZS']

In [10]:
records = []

for ticker in data.columns.levels[0]:
    temp = data[ticker].copy()

    # 如果整只股票全空，就跳过
    if temp.isna().all().all():
        print(f"Skipping empty ticker: {ticker}")
        continue

    temp["ticker"] = ticker
    temp = temp.reset_index()
    records.append(temp)

prices = pd.concat(records, ignore_index=True)
prices.head()

Skipping empty ticker: JNPR

Price,Date,Open,High,Low,Close,Adj Close,Volume,ticker
0,2018-01-02,65.129997,65.940002,64.699997,65.559998,65.559998,1425900.0,AKAM
1,2018-01-03,65.269997,66.000000,65.099998,65.940002,65.940002,2287700.0,AKAM
2,2018-01-04,66.160004,66.250000,65.440002,65.599998,65.599998,1870600.0,AKAM
3,2018-01-05,65.699997,65.860001,65.459999,65.830002,65.830002,1056000.0,AKAM
4,2018-01-08,65.949997,66.089996,65.209999,65.879997,65.879997,1185900.0,AKAM

In [11]:
prices.columns = [str(col).lower().replace(" ", "_") for col in prices.columns]
prices.head()

,date,open,high,low,close,adj_close,volume,ticker
0,2018-01-02,65.129997,65.940002,64.699997,65.559998,65.559998,1425900.0,AKAM
1,2018-01-03,65.269997,66.000000,65.099998,65.940002,65.940002,2287700.0,AKAM
2,2018-01-04,66.160004,66.250000,65.440002,65.599998,65.599998,1870600.0,AKAM
3,2018-01-05,65.699997,65.860001,65.459999,65.830002,65.830002,1056000.0,AKAM
4,2018-01-08,65.949997,66.089996,65.209999,65.879997,65.879997,1185900.0,AKAM

In [12]:
print(prices.columns.tolist())

['date', 'open', 'high', 'low', 'close', 'adj_close', 'volume', 'ticker']

In [13]:
prices = prices[["date", "ticker", "open", "high", "low", "close", "adj_close", "volume"]]
prices = prices.sort_values(["ticker", "date"]).reset_index(drop=True)
prices.head()

,date,ticker,open,high,low,close,adj_close,volume
0,2018-01-02,AKAM,65.129997,65.940002,64.699997,65.559998,65.559998,1425900.0
1,2018-01-03,AKAM,65.269997,66.000000,65.099998,65.940002,65.940002,2287700.0
2,2018-01-04,AKAM,66.160004,66.250000,65.440002,65.599998,65.599998,1870600.0
3,2018-01-05,AKAM,65.699997,65.860001,65.459999,65.830002,65.830002,1056000.0
4,2018-01-08,AKAM,65.949997,66.089996,65.209999,65.879997,65.879997,1185900.0

In [14]:
print(prices.shape)
print(prices["ticker"].nunique())
print(prices["ticker"].unique())

(38209, 8)
19
['AKAM' 'CHKP' 'CRWD' 'CSCO' 'CYBR' 'FTNT' 'GEN' 'NET' 'NTGR' 'OKTA'
 'OTEX' 'PANW' 'PLTR' 'QLYS' 'RPD' 'S' 'SNPS' 'TENB' 'ZS']

In [15]:
prices.isna().sum()

date            0
ticker          0
open         2552
high         2552
low          2552
close        2552
adj_close    2552
volume       2552
dtype: int64

In [16]:
coverage = prices.groupby("ticker").agg(
    start_date=("date", "min"),
    end_date=("date", "max"),
    rows=("date", "count")
).reset_index()

coverage

   ticker start_date   end_date  rows
0    AKAM 2018-01-02 2025-12-31  2011
1    CHKP 2018-01-02 2025-12-31  2011
2    CRWD 2018-01-02 2025-12-31  2011
3    CSCO 2018-01-02 2025-12-31  2011
4    CYBR 2018-01-02 2025-12-31  2011
5    FTNT 2018-01-02 2025-12-31  2011
6     GEN 2018-01-02 2025-12-31  2011
7     NET 2018-01-02 2025-12-31  2011
8    NTGR 2018-01-02 2025-12-31  2011
9    OKTA 2018-01-02 2025-12-31  2011
10   OTEX 2018-01-02 2025-12-31  2011
11   PANW 2018-01-02 2025-12-31  2011
12   PLTR 2018-01-02 2025-12-31  2011
13   QLYS 2018-01-02 2025-12-31  2011
14    RPD 2018-01-02 2025-12-31  2011
15      S 2018-01-02 2025-12-31  2011
16   SNPS 2018-01-02 2025-12-31  2011
17   TENB 2018-01-02 2025-12-31  2011
18     ZS 2018-01-02 2025-12-31  2011

In [17]:
coverage.to_csv(processed_path / "ticker_coverage.csv", index=False)
print("Saved ticker coverage report.")

Saved ticker coverage report.

In [18]:
prices.to_csv(processed_path / "prices_clean.csv", index=False)
print("Saved cleaned data to:", processed_path / "prices_clean.csv")

Saved cleaned data to: ..\data\processed\prices_clean.csv

In [19]:
downloaded_tickers = sorted(prices["ticker"].unique().tolist())
downloaded_tickers

['AKAM',
 'CHKP',
 'CRWD',
 'CSCO',
 'CYBR',
 'FTNT',
 'GEN',
 'NET',
 'NTGR',
 'OKTA',
 'OTEX',
 'PANW',
 'PLTR',
 'QLYS',
 'RPD',
 'S',
 'SNPS',
 'TENB',
 'ZS']

In [20]:
universe_filtered = universe[universe["ticker"].isin(downloaded_tickers)].copy()
universe_filtered

   ticker             company           subtheme
0    CRWD         CrowdStrike           endpoint
1    PANW  Palo Alto Networks           platform
2    FTNT            Fortinet            network
3    TENB             Tenable           endpoint
4       S         SentinelOne           endpoint
5    OKTA                Okta           identity
6    CYBR            CyberArk           identity
7      ZS             Zscaler              cloud
8     NET          Cloudflare       network_edge
9    AKAM              Akamai       network_edge
10   CSCO               Cisco            network
12   NTGR             Netgear            network
13   SNPS            Synopsys         secure_dev
14   PLTR            Palantir      data_platform
15   OTEX            OpenText      data_security
16    RPD              Rapid7       security_ops
17   CHKP         Check Point            network
18    GEN         Gen Digital  consumer_security
19   QLYS              Qualys     cloud_security

In [21]:
universe_filtered.to_csv(processed_path / "universe_filtered.csv", index=False)
print("Saved filtered universe.")

Saved filtered universe.

In [22]:
prices.columns.tolist()

['date', 'ticker', 'open', 'high', 'low', 'close', 'adj_close', 'volume']

In [23]:
coverage

   ticker start_date   end_date  rows
0    AKAM 2018-01-02 2025-12-31  2011
1    CHKP 2018-01-02 2025-12-31  2011
2    CRWD 2018-01-02 2025-12-31  2011
3    CSCO 2018-01-02 2025-12-31  2011
4    CYBR 2018-01-02 2025-12-31  2011
5    FTNT 2018-01-02 2025-12-31  2011
6     GEN 2018-01-02 2025-12-31  2011
7     NET 2018-01-02 2025-12-31  2011
8    NTGR 2018-01-02 2025-12-31  2011
9    OKTA 2018-01-02 2025-12-31  2011
10   OTEX 2018-01-02 2025-12-31  2011
11   PANW 2018-01-02 2025-12-31  2011
12   PLTR 2018-01-02 2025-12-31  2011
13   QLYS 2018-01-02 2025-12-31  2011
14    RPD 2018-01-02 2025-12-31  2011
15      S 2018-01-02 2025-12-31  2011
16   SNPS 2018-01-02 2025-12-31  2011
17   TENB 2018-01-02 2025-12-31  2011
18     ZS 2018-01-02 2025-12-31  2011

In [24]:
prices.head()

,date,ticker,open,high,low,close,adj_close,volume
0,2018-01-02,AKAM,65.129997,65.940002,64.699997,65.559998,65.559998,1425900.0
1,2018-01-03,AKAM,65.269997,66.000000,65.099998,65.940002,65.940002,2287700.0
2,2018-01-04,AKAM,66.160004,66.250000,65.440002,65.599998,65.599998,1870600.0
3,2018-01-05,AKAM,65.699997,65.860001,65.459999,65.830002,65.830002,1056000.0
4,2018-01-08,AKAM,65.949997,66.089996,65.209999,65.879997,65.879997,1185900.0